import SlamLocksPage from "../../components/SlamLocksPage";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteLayout } from "../../components/SiteChrome";
import { EstimateBanner, PageBanner, Testimonials } from "../../components/ReferenceSections";
import { services } from "../../site-data";
import DeadLocksPage from "../../components/DeadLocksPage";

const serviceCopy: Record<string, { heading: string; intro: string; benefits: string[]; closing: string }> = {
  "van-dead-locks": { heading: "Secure Your Van with Heavy-Duty DeadLocks", intro: "A dead lock adds a separate, key-operated locking point to the van door. Its straight bolt engages with the van body, working independently from the factory central locking system. Vehicle-specific fitting kits help keep installation neat and protect the door structure.", benefits: ["Independent from the factory central locking system.", "Straight bolt secures into the van body.", "Operated using a separate high-security key.", "Keyed-alike options are available for fleets.", "Vehicle-specific kits suit different van models."], closing: "Protect Your Van — Upgrade Now!" },
  "van-hook-locks": { heading: "Additional Security with Van Hook Locks", intro: "A hook lock is a manually operated mechanical lock that works separately from the van’s factory locking system. Its hook-shaped bolt engages with the body section, adding a separate locking point to the door.", benefits: ["Works independently from the factory locking system.", "Hook-shaped bolt engages with the opposing body section.", "Driver controls locking with a separate key.", "Vehicle-specific kits are available for different models."], closing: "Protect Your Van — Upgrade Now!" },
  "van-slam-locks": { heading: "Automatic Security with Van Slam Locks", intro: "A slam lock secures the door automatically when it closes. It can suit drivers who make frequent stops and need the loading door to lock as part of their working routine.", benefits: ["Automatically locks the door when it closes.", "Opened with its dedicated key.", "Suited to frequently used loading doors."], closing: "Protect Your Van — Upgrade Now!" },
  "van-statement-lock": { heading: "Visible Protection with Van Statement Locks", intro: "A statement lock is fitted to the outside of the van doors and braces them together. Its visible position also makes the additional lock apparent before an attempt is made to open the doors.", benefits: ["Surface-mounted across the van doors.", "Adds an additional mechanical locking point.", "Visible external fitment acts as a deterrent."], closing: "Protect Your Van — Upgrade Now!" },
  "replacement-lock-for-ford": { heading: "Replacement Lock for Ford Vans", intro: "A damaged, worn or compromised lock can put a Ford van’s security at risk. VanLock supplies and fits replacement locks for Ford Transit, Custom, Connect and other commercial models, restoring the door’s locking function with a model-specific replacement.", benefits: ["Smooth locking and unlocking with quality keys.", "Built for frequent use and working conditions.", "Fitted efficiently to reduce disruption.", "Restores the original lock’s function after damage or wear.", "Designed to resist common picking and drilling attempts."], closing: "Protect Your Van — Upgrade Now!" },
  "repair-plate-or-external-shield": { heading: "Reinforce Damaged or Vulnerable Van Doors", intro: "Repair plates and external shields reinforce vulnerable areas around van locks and handles. They can also cover damage left by a previous break-in, without replacing the whole door section.", benefits: ["Covers vulnerable areas around handles, locks and panels.", "Adds a reinforcing layer over weak points.", "Can cover damage from a previous break-in.", "Quick installation without replacing a door section.", "Vehicle-specific options for different van models."], closing: "Repair & Protect Your Van — All in One Step." },
  "air-vent-installation": { heading: "Improve Ventilation & Safety in Your Van", intro: "Air Vent Installation is a smart upgrade for any van that transports tools, animals, chemicals, or anything sensitive to heat or poor airflow. Professionally installed air vents help maintain internal temperature, prevent condensation, and improve overall air quality.", benefits: ["Improved Air Circulation: Enhances ventilation by allowing stale, hot air to escape and fresh air to flow in.", "Reduces Moisture Buildup: Helps prevent rust, mold, and condensation inside your cargo space.", "Protects Equipment and Cargo: Keeps tools, electronics, and stored goods at a safer temperature.", "Custom Placement for Maximum Efficiency: Vents can be installed in roofs or side panels depending on your van’s use case."], closing: "Breathe New Life into Your Van" },
};

export function generateStaticParams() { return services.map(({ slug }) => ({ slug })); }
export default async function ServiceDetailPage({ params }: PageProps<"/our-services/[slug]">) {
  const { slug } = await params;
  const service = services.find(item => item.slug === slug);
  if (!service) notFound();
  if (slug === "van-dead-locks") return <DeadLocksPage />;
  if (slug === "van-hook-locks") return <DeadLocksPage variant="hooklocks" />;
  if (slug === "van-slam-locks") return <SlamLocksPage />;
  const copy = serviceCopy[slug];
  return <SiteLayout><main><PageBanner title={service.title} image={slug === "air-vent-installation" ? "/vanlock/fleet-van.jpg" : "/vanlock/hook-lock.jpg"}/><section className="route-content"><div className="container service-detail"><div><p className="eyebrow">OUR SERVICES</p><h2>{copy?.heading ?? service.title}</h2>{copy && <p>{copy.intro}</p>}<h3>Key Features &amp; Benefits</h3>{copy ? <ul>{copy.benefits.map(item => <li key={item}>✓ <span>{item}</span></li>)}</ul> : null}<h3>{copy?.closing ?? service.title}</h3><Link className="button" href="/contact">Get a Quote <span>→</span></Link></div><img src={slug === "air-vent-installation" ? "/vanlock/fleet-van.jpg" : "/vanlock/hook-lock.jpg"} alt={service.title}/></div></section><Testimonials/><section className="route-related"><h2>Our Services</h2><div>{services.filter(item => item.slug !== slug).map(item => <Link href={`/our-services/${item.slug}`} key={item.slug}>{item.title} →</Link>)}</div></section><EstimateBanner/></main></SiteLayout>;
}
